Split ExtendedSQLiteOpenHelper into two classes
novoda/sqlite-provider pull request #68
Opened 2016-12-05 21:44 UTC by friedger

This PR splits ExtendedSQLiteOpenHelper into two classes: MigratingSQLiteOpenHelper and SQLiteDatabaseMetaInfo. This separates the concerns and allows to provide customized open helpers.

While splitting the class the deprecated APIs have not been moved, but removed where possible.

Tests have not been added or separated to show that all tests still pass.

This fixes #57

2016-12-05 21:44 UTC, stefanhoth commented
Can one of the admins review this PR?

2016-12-19 09:36 UTC, friedger commented
any comments?

2017-01-04 13:16 UTC, rock3r commented
hal test this please

2017-01-04 14:01 UTC, rock3r reviewed
Seems OK to me, once the stray Javadoc is taken out it's good to go

2017-01-04 14:01 UTC, rock3r commented on core/src/main/java/novoda/lib/sqliteprovider/provider/action/InsertHelper.java
> +    public InsertHelper(SQLiteOpenHelper databaseHelper, SQLiteDatabaseMetaInfo metaInfo) {
These changes require a major release ⚠️  -- it's fine since #69 and #70 will require one anyway

2017-01-04 14:01 UTC, rock3r commented on core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java
> +/**
Can you please take this out @friedger?

2017-01-04 14:01 UTC, rock3r commented on core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java
> +        return DBUtils.getFields(helper.getReadableDatabase(), table);
Might clash with the work in #69 but I suppose @eduardb can adjust accordingly

2017-01-04 14:04 UTC, eduardb commented on core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java
> +        return DBUtils.getFields(helper.getReadableDatabase(), table);
Yes, we can get this PR merged first. It should go smoother 😄

2017-01-04 14:09 UTC, eduardb approved these changes
Besides what @rock3r already said, it looks great to me 👍

2017-01-04 14:11 UTC, rock3r requested changes
Need to remove the autogenerated "author" javadoc

2017-01-04 14:12 UTC, rock3r commented
Sorry I had forgotten to click "request changes" before :D

2017-01-05 22:39 UTC, friedger commented
Comments addressed :-)

2017-01-09 15:03 UTC, rock3r approved these changes

2017-01-09 15:03 UTC, rock3r commented
hal test this please

2017-01-09 15:03 UTC, rock3r commented
Thanks @friedger

2017-01-09 15:05 UTC, rock3r commented
:shipit:

2017-01-09 15:05 UTC, merged